language: python
python:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=pypy
before_install:
  - sudo apt-get install nodejs
install:
  - pip install tox
script: tox -e $TOX_ENV
notifications:
  email: true
