language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
before_install:
  - sudo apt-get install nodejs
install: "python setup.py install"
script: purelyjs
notifications:
  email: false
