language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
env:
  - INTERPRETER=/usr/bin/js
  - INTERPRETER=/usr/bin/rhino
before_install:
  - sudo apt-get install nodejs rhino
install: "python setup.py install"
script: purelyjs -i $INTERPRETER
notifications:
  email: true
